name: Debug VS 2026 Environment

on:
  workflow_dispatch:
    inputs:
      link:
        description: 'Link'
        required: true

jobs:
  explore:
    runs-on: ubuntu-lastest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download archive
        run: |
          wget --progress=dot:mega ${{ inputs.link }}
          unzip *.zip

      - uses: fawazahmed0/action-debug-vscode@main
