name: OrangeFox Sync Lean

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize space # Обязательно для 14.1 (чистит ~20ГБ)
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 2048
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'

      - name: Install minimal dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y aria2 # Используется скриптом для ускорения загрузки

      - name: Install Repo
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Sync
        run: |
          mkdir OF && cd OF
          git clone https://gitlab.com/OrangeFox/sync.git sync --depth=1
          cd sync
          export LC_ALL=C
          ./orangefox_sync.sh --branch 14.1 --path ../fox_14.1 --depth=1

      - name: Cleanup and Upload
        run: |
          rm -rf OF/fox_14.1/.repo # Удаляем гигабайты истории перед загрузкой
          mv OF/fox_14.1 ./upload_dir

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OrangeFox-14.1-Sources
          path: upload_dir/
          retention-days: 1
